### ISSUE TITLE
generate_stinky_orders: inconsistencies

### ISSUE THREAD

**Issue by meetkakadiya44** [beatzxbt/bybit-smm#24]
https://github.com/beatzxbt/bybit-smm/blob/v.2.0-alpha/smm/quote_generators/stinky.py

def generate_stinky_orders
nothing is returned. shouldn't the variables orders be returned?

secondly, the parameter['base_spread'] is utilized directly, but there are min/max  spreads in parameters.yaml. 

`    def generate_stinky_orders(self) -> List[Dict]:
        """
        Generate deep orders in a range from the base spread to base^1.5 away from mid.

        This method generates a series of bid and ask orders based on geometric spreads 
        and sizes, ranging from a base spread to a spread raised to the power of 1.5.

        Returns
        -------
        List[Dict]
            A list of single quotes.
        """
        orders = []

        spreads = nbgeomspace(
            start=self.bps_to_decimal(self.params["base_spread"]),
            end=self.bps_to_decimal(self.params["base_spread"] ** 1.5),
            n=self.total_orders//2
        )

        sizes = self.max_position * generate_geometric_weights(num=self.total_orders//2)

        for spread, size in zip(spreads, sizes):
            bid_price = self.mid - spread
            ask_price = self.mid + spread

            orders.append(
                self.generate_single_quote(
                    side=0.0,
                    orderType=0.0,
                    price=round_floor(num=bid_price, step_size=self.data["tick_size"]),
                    size=round_ceil(num=size, step_size=self.data["lot_size"]),
                )
            )

            orders.append(  
                self.generate_single_quote(
                    side=1.0,
                    orderType=0.0,
                    price=round_ceil(num=ask_price, step_size=self.data["tick_size"]),
                    size=round_ceil(num=size, step_size=self.data["lot_size"]),
                )
            )

**Comment by beatzxbt** [comment]
this was caught in testing, ill be pushing it in the next few bug fix cycles!
